### ISSUE TITLE
Relationship / intersection with Media Capture Depth

### ISSUE THREAD

**Issue by dontcallmedom** [bialpio/webxr-depth-api#1]
The WebRTC Working Group developed a few years ago an extension to Media Capture and Streams to be able to capture depth data from depth cameras:
  https://w3c.github.io/mediacapture-depth/

I understand there is an experimental implementation of that spec in Chromium (cc @riju).

There is likely some overlap between this proposal and that API that might be useful to explore.

**Comment by bialpio** [comment]
Moved to immersive-web/depth-sensing#1.
